-- ai-platform-engineering-portfolio has no database of its own.
-- See each linked case study's sql/example-schema.sql.
-- This schema is a sanitized learning version based on independent development work. It does not contain production data, private credentials, proprietary logic, or real customer records.
